// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1beta1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"demo-operator-frontend/pkg/apis/demo/v1beta1.MyDemoFrontend":       schema_pkg_apis_demo_v1beta1_MyDemoFrontend(ref),
		"demo-operator-frontend/pkg/apis/demo/v1beta1.MyDemoFrontendSpec":   schema_pkg_apis_demo_v1beta1_MyDemoFrontendSpec(ref),
		"demo-operator-frontend/pkg/apis/demo/v1beta1.MyDemoFrontendStatus": schema_pkg_apis_demo_v1beta1_MyDemoFrontendStatus(ref),
	}
}

func schema_pkg_apis_demo_v1beta1_MyDemoFrontend(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "MyDemoFrontend is the Schema for the mydemofrontends API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("demo-operator-frontend/pkg/apis/demo/v1beta1.MyDemoFrontendSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("demo-operator-frontend/pkg/apis/demo/v1beta1.MyDemoFrontendStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"demo-operator-frontend/pkg/apis/demo/v1beta1.MyDemoFrontendSpec", "demo-operator-frontend/pkg/apis/demo/v1beta1.MyDemoFrontendStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_demo_v1beta1_MyDemoFrontendSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "MyDemoFrontendSpec defines the desired state of MyDemoFrontend",
				Properties: map[string]spec.Schema{
					"label": {
						SchemaProps: spec.SchemaProps{
							Description: "Label is the value of the 'daemon=' label to set on a node that should run the daemon",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"image": {
						SchemaProps: spec.SchemaProps{
							Description: "Image is the Docker image to run for the daemon",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"backend": {
						SchemaProps: spec.SchemaProps{
							Description: "Image is the Docker backend image to run for the daemon",
							Type:        []string{"string"},
							Format:      "",
						},
					},
				},
				Required: []string{"label", "image", "backend"},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_demo_v1beta1_MyDemoFrontendStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "MyDemoFrontendStatus defines the observed state of MyDemoFrontend",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
