// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MyDemoFrontend) DeepCopyInto(out *MyDemoFrontend) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MyDemoFrontend.
func (in *MyDemoFrontend) DeepCopy() *MyDemoFrontend {
	if in == nil {
		return nil
	}
	out := new(MyDemoFrontend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MyDemoFrontend) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MyDemoFrontendList) DeepCopyInto(out *MyDemoFrontendList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MyDemoFrontend, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MyDemoFrontendList.
func (in *MyDemoFrontendList) DeepCopy() *MyDemoFrontendList {
	if in == nil {
		return nil
	}
	out := new(MyDemoFrontendList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MyDemoFrontendList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MyDemoFrontendSpec) DeepCopyInto(out *MyDemoFrontendSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MyDemoFrontendSpec.
func (in *MyDemoFrontendSpec) DeepCopy() *MyDemoFrontendSpec {
	if in == nil {
		return nil
	}
	out := new(MyDemoFrontendSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MyDemoFrontendStatus) DeepCopyInto(out *MyDemoFrontendStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MyDemoFrontendStatus.
func (in *MyDemoFrontendStatus) DeepCopy() *MyDemoFrontendStatus {
	if in == nil {
		return nil
	}
	out := new(MyDemoFrontendStatus)
	in.DeepCopyInto(out)
	return out
}
