apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8sdemo-backend
  namespace: default
  labels:
    app: k8sdemo-backend
spec:
  selector:
    matchLabels:
      app: k8sdemo-backend
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: "30%"
      maxSurge: "90%"
  template:
    metadata:
      labels:
        app: k8sdemo-backend
        version: current
    spec:
      containers:
      - name: k8sdemo-backend
        image: docker.io/niklaushirt/k8sdemo-backend:1.0.0
        imagePullPolicy: IfNotPresent 
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 100
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 100
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "150m"
            memory: "150Mi"
          limits:
            cpu: "500m"
            memory: "500Mi"
        env:
          - name: PORT
            value : "3000"
          - name: APPLICATION_NAME
            value: k8sdemo-backend
          - name: BACKEND_MESSAGE
            value: "Hi there from the Security Training..."