apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8sdemo-nok
  namespace: default
  labels:
    app: k8sdemo-nok
spec:
  selector:
    matchLabels:
      app: k8sdemo-nok
  replicas: 1
  template:
    metadata:
      labels:
        app: k8sdemo-nok
    spec:
      containers:
      - name: k8sdemo-nok
        image: niklaushirt/k8sdemo:1.0.1
        ports:
        - containerPort: 3000 
        env:
          - name: PORT
            value : "3000"
          - name: APPLICATION_NAME
            value: k8sdemo-nok
          - name: BACKEND_URL
            value: http://k8sdemo-nok-backend-service.default.svc:3000/api
