apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: default
  labels:
      app: my-nginx
      release: april2023
spec:
  containers:
  - name: nginx
    image: docker.io/nginx:latest
    ports:
    - containerPort: 80